### ISSUE TITLE
Repo name conflict

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#1]
This conflicts with https://github.com/ga-wdi-boston/installfest/issues/23

I gather this is an new hire orientation. Thoughts on names, either for this or for the soon-to-be-former installfest?

**Comment by gaand** [comment]
Sorry, didn't know what to call it and wanted to get the thought recorded

This is for students.  Make sure they know they're expected to check slack.

**Comment by jrhorn424** [comment]
Thanks for clarification. I'd say there's no conflict then. 😉
