### ISSUE TITLE
Select a sublime package for expressjs

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/orientation#10]
If an appropriate one exists

**Comment by gaand** [comment]
Maybe this one?
  https://github.com/terminalvelocity/ember-cli-sublime-snippets

**Comment by jrhorn424** [comment]
OBE. @gaand is this still desirable for atom? If so, should we have snippets for other frameworks?

**Comment by RealWeeks** [comment]
Legacy issue, now using atom.

**Comment by gaand** [comment]
We should see if there are support packages for atom.  **Not** legacy.

**Comment by jrhorn424** [comment]
@gaand Feel free to reopen, but I don't recall needing to install anything during the last iteration.
