### ISSUE TITLE
Add permission prior to installing brew

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/orientation#102]

**Comment by jrhorn424** [comment]
`chmod -R $(whoami):admin /usr/local`

This needs to be tested on a machine that has never seen brew before.

**Comment by RealWeeks** [comment]
@laurenfazah potential issue for tomorrow

**Comment by RealWeeks** [comment]
Homebrew no longer needs to have ownership of /usr/local.

**Comment by RealWeeks** [comment]
@berziiii @jrhorn424 Consider closing and related issues.

**Comment by jrhorn424** [comment]
Homebrew does not need ownership, but your user account does. If the logged-in user doesn't own `/usr/local`, it must use `sudo brew install ...` which is not conventional for `brew`.
