### ISSUE TITLE
Remove `language-ember-htmlbars` from installfest

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#104]
Until #94 is resolved.

**Comment by gaand** [comment]
@jrhorn424, @berziiii  Is the utility provided by this package subsumed by language-ember-htmlbars?

**Comment by jrhorn424** [comment]
> @jrhorn424, @berziiii Is the utility provided by this package subsumed by language-ember-htmlbars?

I'm confused. `language-ember-htmlbars` is what we removed.

AFAIK, the utility provided by this package isn't available anywhere else. We will install the package when it is necessary during ember week. The package screws up HTML commenting in non-HBS files (#94), causing issues in the first three units.

**Comment by gaand** [comment]
@jrhorn424 the title of this issue says `language-html-bars', not`language-ember-htmlbars` which is why I asked.

**Comment by jrhorn424** [comment]
Indeed. Thanks @gaand!
