### ISSUE TITLE
Remove brew cask from installfest?

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#105]
@ga-wdi-boston/core Do we still use cask for anything? I'm about 95% we don't.

**Comment by jrhorn424** [comment]
The motivation for this change is out-of-date installation instructions in the README.

**Comment by gaand** [comment]
@jrhorn424 I thought you opened an issue (somewhere, not necessarily here) asking if we should install more things using brew (and therefore brew cask).

**Comment by jrhorn424** [comment]
I don't recall. I'll leave this open for now, and I'll search through the other repos later.

**Comment by raq929** [comment]
Installing cask has been removed from installfest. Can this issue be closed?

**Comment by jrhorn424** [comment]
Yes. :smile:
