### ISSUE TITLE
The instruction "Open ~/.bashrc" needs clarification.

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/orientation#106]
The readme says: "Open ~/.bashrc..."
Either explicitly say type "open ~/.bashrc" into the terminal, or change this to "atom ~/.bashrc"

Side note:
If we want this file to automatically open in atom we need to make that change in the atom section as well.

**Comment by jrhorn424** [comment]
> If we want this file to automatically open in atom we need to make that change in the atom section as well.

What do you mean?

**Comment by gaand** [comment]
I think I prefer the explicit command. Especially since sometimes the "wrong" executable is started.

**Comment by payne-chris-r** [comment]
#teachAbleMOments
I like it @gaand.

**Comment by gaand** [comment]
@payne-chris-r I'm confused.  You closed this but the repo hasn't been updated.

**Comment by raq929** [comment]
The repo now says `atom ~/.bashrc`
