### ISSUE TITLE
GitHub Passphrase is causing problems.

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/orientation#137]
After the following command:
**_ssh-keygen -t rsa -C "your_email@example.com"**
(Feel free to put in a password or select a non-default location for your keys, but it's not necessary to do so; to move ahead, just keep hitting enter)._

People are running into issues. More instruction on what each of these steps means and how to navigate them is necessary.

**Comment by RealWeeks** [comment]
@payne-chris-r Can you go into a bit more depth on what issues people ran into? 

Note: @j-weeks add to this tomorrow

**Comment by payne-chris-r** [comment]
@J-Weeks: https://github.com/ga-wdi-boston/orientation/issues/139

**Comment by raq929** [comment]
I believe this was not an issue for `lm01` or for `017` and can be closed.
