### ISSUE TITLE
Update versions for next cohort

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#138]
Versions were the same for cohort 11 and cohort 12.
- Ruby 2.3.0
- Node 4.4.4

**Comment by RealWeeks** [comment]
node 4.4.7
ruby 2.3.0
rails 4.2.6

@jrhorn424 Thoughts? After discussion with @laurenfazah and @gaand no rails upgrade... yet

**Comment by RealWeeks** [comment]
@jrhorn424 addressed in commit 486f31d. Okay to close?

**Comment by jrhorn424** [comment]
Thanks @J-Weeks!
