### ISSUE TITLE
Improve instructions for generating an ssh key and uploading to GitHub

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#139]
This is covered in Fundamentals. <del>Many developers will therefore not need to do it.</del>

Related #137

Developers must cover this sections regardless of what Fundamentals covers.

**Comment by payne-chris-r** [comment]
Correct. I would say this section in general could use attention. See #141 as well when fixing this section.

**Comment by RealWeeks** [comment]
@jrhorn424 @payne-chris-r any specific pain points of suggestions to improve?

**Comment by payne-chris-r** [comment]
In particular, the necessity of a password @J-Weeks. We had some people create passwords, some didn't, some didn't remember the passwords they created (cause you can't see it type out).

**Comment by RealWeeks** [comment]
Agreed, I'll try work on this before we get into the thick of it. I will also refrain from including instructions on when to breathe and how to turn on a light switch.

**Comment by raq929** [comment]
Add a sentence where we say "Use the email you used to sign up to gitHub with. Do not include the `<>`. The `<>` indicate text that you need to change before running the script. Per @jrhorn424

**Comment by scottyscripts** [comment]
moved to and closed on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/139
