### ISSUE TITLE
Combine amendments to `/.bashrc in Git section

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/orientation#14]
Rather than doing
`echo "export EDITOR='subl -w'" >> ~/.bashrc`
we could just add
`export EDITOR='subl -w'` to the previous section of code being pasted into .bashrc

**Comment by jrhorn424** [comment]
As noted in #47, this refers to the wrong EDITOR variable.

**Comment by jrhorn424** [comment]
Closing, since the bug is incidentally related and  noted elsewhere.
