### ISSUE TITLE
Add prompt to fork and clone repo to copy config dotfiles to locals

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/orientation#140]

**Comment by gaand** [comment]
@jrhorn424 I'm wondering why this makes sense but default-gems doesn't?

**Comment by jrhorn424** [comment]
@gaand I revised my position on rbenv-default-gems over here https://github.com/ga-wdi-boston/orientation/issues/72#issuecomment-218860063

**Comment by RealWeeks** [comment]
@berziiii added with commit 6b6904a but I only added a note to have the instructor lead them on forking and clone not the actual directions on how to do it since the lesson come the following Monday.

**Comment by jrhorn424** [comment]
Thanks @J-Weeks
