### ISSUE TITLE
Add permissions check to ssh section

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#141]
> Typically you want the .ssh directory permissions to be 700 (drwx------) and the public key (.pub file) to be 644 (-rw-r--r--). Your private key (id_rsa) should be 600 (-rw-------).

**Comment by payne-chris-r** [comment]
One of the issues is that the type of permissions/key they use for Fundamentals is different from the one we use. It's not id.rsa in fundamentals, so we need to make sure they are getting the correct SSH set up during orientation.

**Comment by scottyscripts** [comment]
moved to and closed on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/141
