### ISSUE TITLE
Add atom configuration section

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#142]
At the very least, developers need to enable options related to having Command+W close a window. By default, it only closes tabs. See screenshot in https://github.com/atom/atom/issues/9761#issue-118379184, the issue is not a concern.

**Comment by gaand** [comment]
Is this a Mac consistency thing or is there another reason this is important?

**Comment by jrhorn424** [comment]
It is important because we're using atom as the commit message editor, and if you don't close the window, git doesn't get the signal that commit message is finished. Closing the tab is insufficient.

**Comment by gaand** [comment]
Could this be handled with instruction?

I don't feel that strongly about it, but I'm wary of non-standard configurations for developers.  Sometimes I don't think I should have a non-standard config, but then I get over it ;-).

**Comment by BenGitsCode** [comment]
I still use CMD+W to close tabs, for cleaning up my workspace for instance but have this

``` cson
'body':
  'cmd-ctrl-w': 'tabs:close-all-tabs'
```

 keymap set in my keymap.cson file in atom. It's an easy fix, and you could just as easily switch those keymappings but I'll leave that up to you guys.

@jrhorn424 @gaand thoughts?

**Comment by gaand** [comment]
@BenGitsCode I think Command-W to close a window and Ctrl-W to close a tab (maybe?  Again, I have some non-WDI-standard things going on, not least because I have a linux box at home).

@jrhorn424 :question:

**Comment by BenGitsCode** [comment]
@gaand I think that best addresses @jrhorn424 's concern.

I can confirm this working with no conflicts so far.

``` cson
'body':
  'cmd-shift-w': 'tabs:close-all-tabs'
  'cmd-w': 'window:close'
  'ctrl-w': 'tabs:close-tab'
```

**Comment by jrhorn424** [comment]
My original intent here was that there is an option for `cmd-w` closes a window. @BenGitsCode Can you confirm that, with your configuration and two tabs open, pressing `cmd-w` twice closes the tabs and leaves the window open, and pressing it a third time closes the window?

**Comment by BenGitsCode** [comment]
@jrhorn424 It does not. Current config will close first tab on `cmd+w` second time will close remaining tab, then it does nothing. I'm guessing you want it that way so that they can close full atom windows without quitting the program entirely?

Without even adding anything beyond the `cmd+w`keymap, `cmd+shift+w` is already the system keymapping for closing an active window. 

I just confirmed that this works on Atom and will close the active window only, would that be satisfactory?

**Comment by BenGitsCode** [comment]
Aha! We're overcomplicating it, or perhaps Atom is. 

No keymapping changes necessary. Apparently `cmd-w` in Atom now triggers the `Core : Close` command. 

Then there's this little guy hiding in plain sight in the core settings:
![close empty windows](https://cloud.githubusercontent.com/assets/159434/11303872/94600abc-8fa5-11e5-9412-62734caa656a.png)

With that setting enabled, and my `keymap.cson` changes removed, I get precisely the behavior described.

`cmd+w`wil systematically close each active window, when none remain it will close that active window, leaving any other atom windows untouched.

**Comment by raq929** [comment]
zomg y'all some of us can use the mouse to close windows. 😉

**Comment by raq929** [comment]
I am going to include Ben's solution unless someone disagrees strongly.

**Comment by BenGitsCode** [comment]
@raq929 wat is a mouse? You've trained a mouse to step on hotkeys for you? I'm impressed :grin:

**Comment by BenGitsCode** [comment]
Unless anyone else jumps in, I think that addresses both Antony and Jeff's concerns. It gives them access to a way of closing the  tab and window when writing commit messages and is also using the standard Atom mappings so it's not a configuration that breaks away from the standard at all.

**Comment by jrhorn424** [comment]
Yes please, this one: https://github.com/ga-wdi-boston/orientation/issues/142#issuecomment-270804395

**Comment by raq929** [comment]
This too: 
if anyone is ever having issues with .env files not showing up in atom, it can be resolved by adding this to the `config.cson` file in atom.
```'tree-view':
  'hideVcsIgnoredFiles': false```

**Comment by jrhorn424** [comment]
It's unclear to me what the next action item is here. I recommend closing this issue.

**Comment by jrhorn424** [comment]
Perhaps any action items should be targeted at the automation script for atom. I think I like hiding VCS files, since it forces developers to open the file manually with atom. `atom .env` still works.

**Comment by scottyscripts** [comment]
moved to and closed on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/142
