### ISSUE TITLE
Make node use readline

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#143]
So searching through history works.

``` sh
brew install rlwrap
```

``` sh
alias node='env NODE_NO_READLINE=1   NODE_REPL_HISTORY_SIZE=10000   rlwrap   node'
```

**Comment by gaand** [comment]
I handle this using a differet mechanism (which I'll figure out in the morning). I tried this way and ran into trouble.

**Comment by RealWeeks** [comment]
@gaand anything to add before tomorrow?

**Comment by jrhorn424** [comment]
@gaand Any news?

**Comment by RealWeeks** [comment]
Anything on this?

**Comment by gaand** [comment]
@J-Weeks I'm pretty sure that this `just works` in current versions of node.  Can we try it on a FL machine or some such?

**Comment by RealWeeks** [comment]
@gaand I think you're right.  When my computer broke I used a FL computer during the node portion of class no issues.

**Comment by gaand** [comment]
This probably could have been closed much earlier.  My apologies.  I haven't carefully review notifications for the orientation repository.  I will from now on.
