### ISSUE TITLE
We may want to use a linter other than atom-jshint

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/orientation#144]
Stopped being supported/updated in Dec, 2015.
2 of the devs in this cohort have already had issues with this error that are identical to the repos issues: #116-121
https://github.com/Joezo/atom-jshint/issues

**Comment by gaand** [comment]
That is not the linter we use (or shouldn't be).  This is the linter we use:

https://github.com/AtomLinter/linter-jshint

**Comment by gaand** [comment]
@payne-chris-r I have no idea why that is the atom linter in the install fest.  It shouldn't be and should never have been.

**Comment by RealWeeks** [comment]
@payne-chris-r resolved in commit 6a241b5 okay to close?

**Comment by payne-chris-r** [comment]
Yes @J-Weeks
