### ISSUE TITLE
Replace atom-jshint with linter-jshint in apm install

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/orientation#145]
Related to issue #144

**Comment by gaand** [comment]
Most of the linters we'll want to use are official Atom packages and start with `linter-`. 

They all depend on the `linter` package.

**Comment by payne-chris-r** [comment]
@gaand should I have people with this issue JUST run 'apm install linter-jshint' or do they need to uninstall atom-jshint as well?

**Comment by gaand** [comment]
I'd uninstall to avoid conflicting/duplicative errors.

**Comment by RealWeeks** [comment]
@payne-chris-r resolved by commit 6a241b5 okay to close?

**Comment by payne-chris-r** [comment]
Yes @J-Weeks
