### ISSUE TITLE
Formatting with Linux commands is confusing.

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/orientation#147]
If we have something like the following, many people see Linux header, think the rest pertains to Linux users only, and skip the `rbenv install 2.3.0 && rbenv global 2.3.0` command. This happened multiple times during 012's installfest.

5.Install `ruby-build`, a plugin for rbenv.
#### OS X

``` bash
brew install ruby-build
```
#### Linux

``` bash
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
```

Don't worry if the above step doesn't take. Some Linux machines may not need it.

6.Install version 2.3.0 of Ruby and make it the system-wide default using the
command:

``` bash
rbenv install 2.3.0 && rbenv global 2.3.0
```

**Comment by gaand** [comment]
## Add break lines after OS specific instructions?

Is there a standard way of setting things off in markdown?  Maybe quote blocks?

## Linux

```
Instructions
About Linux
```

## OSX

```
Instructions
About OSX
```

**Comment by RealWeeks** [comment]
@gaand I don't think line breaks will work in this case (if I'm following my linters orders), getting a warning for for embedding ## and ###.  I can clear this up though through consistent formatting.

**Comment by RealWeeks** [comment]
@payne-chris-r addressed in commit db6eec5 thoughts?  Either way please keep open, so I can add further comments on it after we set record installfest speed tomorrow. _shots fired_

**Comment by jrhorn424** [comment]
I prefer our instructions be formatted like this:

``` sh
# OSX
brew install foo
```

``` sh
# Linux
sudo apt-get install foo
```

Rather than:

#### OSX

``` sh
brew install foo
```

#### Linux

``` sh
sudo apt-get install foo
```

**Comment by jrhorn424** [comment]
Including the OS as part of the fenced code block makes it clear when linux instructions end.

**Comment by RealWeeks** [comment]
@jrhorn424 partial update in commit 4b044b9. It works really well in some places and others not so much. Example being when there are a number of steps that only one OS needs to follow, in this case it seems more clear to have a headerline.

**Comment by gaand** [comment]
I think that #180 may make this almost entirely obsolete.

**Comment by payne-chris-r** [comment]
This is definitely NOT resolved yet. Minor improvements, but there is still no consistent format throughout.

**Comment by gaand** [comment]
@payne-chris-r Did you read issue #180 ?

**Comment by jrhorn424** [comment]
From what I can tell, #180 combined with something like #170 would achieve a consistent, less confusing format.

**Comment by raq929** [comment]
I believe this will be resolved for the next cohort (LM01), but I'd like someone to doublecheck.

**Comment by jrhorn424** [comment]
I'm ok with closing this issue. @gaand?

@raq929 accomplished a lot of work with this. I think specific confusions should be filed as individual issues during LM01

**Comment by jrhorn424** [comment]
Thanks for your work @raq929. Discussion continues over at #245.
