### ISSUE TITLE
Install phantom.js

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/orientation#148]
For use during ember.  Issue opened per @jrhorn424

**Comment by RealWeeks** [comment]
@jrhorn424 

Deprecation warning for phantomjs:

```
DEPRECATED
Pre-2.0, this package was published to NPM as phantomjs. We changed the name to phantomjs-prebuilt at the request of PhantomJS team.

Please update your package references from phantomjs to phantomjs-prebuilt
```

Before I add this will going with prebuilt mess anything up with Ember that you are aware of?

**Comment by jrhorn424** [comment]
No, but I'm not sure we get this warning anymore. I can leave open until you get to Ember in 013 and we can figure it out then.

**Comment by laurenfazah** [comment]
No phantomjs issues in ember prep for 013 @jrhorn424 @J-Weeks

**Comment by RealWeeks** [comment]
@jrhorn424 added this in commit 837f195. Thoughts? okay to close?
