### ISSUE TITLE
Add instructions to configure chrome web console

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#149]
disable cache and log network requests

<img width="707" alt="google" src="https://cloud.githubusercontent.com/assets/388761/15828315/c771a996-2bdc-11e6-843b-18059be92774.png">

<img width="533" alt="google" src="https://cloud.githubusercontent.com/assets/388761/15828344/e518662e-2bdc-11e6-8ceb-890eb1ffb1a6.png">

**Comment by RealWeeks** [comment]
@jrhorn424 ok to close? added in commit dba85c2

**Comment by jrhorn424** [comment]
Thanks!
