### ISSUE TITLE
Add `nvm alias default stable` and `nvm use default` to NVM section.

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/orientation#15]

**Comment by RealWeeks** [comment]
Already added to doc.

**Comment by gaand** [comment]
@J-Weeks Is this what's in the doc?  If so, it's wrong.  It should be something like:

``` sh
nvm alias lts v4
nvm alias default lts
```

**Comment by jrhorn424** [comment]
@berziiii Can you make this change as part of your README updates? Thanks.

**Comment by berziiii** [comment]
see commit 277d4f0. Does this correct these changes @jrhorn424?

**Comment by jrhorn424** [comment]
Yes, thanks.

**Comment by berziiii** [comment]
corrected commit 48fe6e9.

**Comment by jrhorn424** [comment]
Looks good! You can mention this as fixed in your pull request.
