### ISSUE TITLE
Add this image?

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/orientation#158]
http://media2.policymic.com/c4bfc173c1b89c4356546074c7abc735.jpg

**Comment by gaand** [comment]
Please.

**Comment by RealWeeks** [comment]
@payne-chris-r added in commit 0a330d8. okay to close?

**Comment by gaand** [comment]
If it's in the deck @austinc203 uses, then this is good to close.

**Comment by jrhorn424** [comment]
@gaand It's not in the deck. I suggested to @austinc203 that the image might not show well in a deck. We can put a link to it in the deck if that would suffice?

**Comment by scottyscripts** [comment]
moved to and closed on https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/158
