### ISSUE TITLE
Trim global rc files?

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/orientation#159]
Or remove entirely?  Our template structure may make them unnecessary. 

This caused problems with deploying to heroku (config/secrets.yml in .gitignore).

**Comment by jrhorn424** [comment]
Global gitignore for OS stuff is most important. It's also really nice to have node_modules ignored as a fail safe. If we keep orientation global gitignore up-to-date with https://github.com/ga-wdi-boston/instructors/issues/21, would that be ok?

**Comment by jrhorn424** [comment]
The current `.gitignore` in meta doesn't ignore the `secrets.yml`.

**Comment by jrhorn424** [comment]
@gaand This should be addressed by https://github.com/ga-wdi-boston/orientation/commit/fb2da0b0aac259c4267a2bd6277ebac5969e4f4e

**Comment by gaand** [comment]
@jrhorn424 I'd like to keep the global rc files as sparse as possible, but I'm not opposed to them.

**Comment by jrhorn424** [comment]
I think I may want to track this in `meta` since it's the logical ancestor of all the other templates.

@gaand Do you think OS-specific ignores are appropriate for a global ignore? Anything else additionally that seems appropriate for a global ignore?

**Comment by jrhorn424** [comment]
I believe this has been addressed and is closeable as of https://github.com/ga-wdi-boston/orientation/commit/f4d91b76dd089a64739e1b5db84fbce2d51cd267

I'm basing this on @gaand's comments here: https://github.com/ga-wdi-boston/node-template/issues/12

**Comment by raq929** [comment]
I agree.
