### ISSUE TITLE
Add codewars signup

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#16]

**Comment by jrhorn424** [comment]
@ga-wdi-boston/core If time allows, I'd like to do this today. It also needs to be documented, but not necessarily today.

**Comment by RealWeeks** [comment]
Would they be ready to take the intro kata?

**Comment by RealWeeks** [comment]
Decided not to have developers sign up during installfest, moved to first workshop.  Question may be cause of loss of moral during first day.
