### ISSUE TITLE
Permissions issues with Homebrew (OSX El Capitan and up)

### ISSUE THREAD

**Issue by nlkassad** [ga-wdi-boston/orientation#160]
We ran into updates running updates with Homebrew. 
The particular one that I ran into was because I had a previous version of postgres installed and I had upgraded to El Capitain. Homebrew ran into permissions issues and created a duplicate copy of postgres.
Here's the resolution for the issue I had:
The permissions issue on El Capitan needs to be corrected
https://digitizor.com/fix-homebrew-permissions-osx-el-capitan/

Uninstall postgres with brew then rm rf /usr/local/var/postgres/

https://github.com/pivotal-sprout/sprout-postgresql/issues/3

It may also be needed to unload and then load LaunchAgent
http://stackoverflow.com/questions/19565708/repairing-postgresql-after-upgrade-to-osx-mavericks

Following that repeat the tasks in the GA setup guide
https://github.com/nlkassad/orientation

**Comment by jrhorn424** [comment]
Related: #102 and #141

**Comment by raq929** [comment]
This is no longer relevant as we are using OSX Sierra and did not run into these problems in the last two cohorts.
