### ISSUE TITLE
TURN ON AUTOSAVE

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#161]
![](https://media.giphy.com/media/l41m553h3vnvueBUc/giphy.gif)

**Comment by BenGitsCode** [comment]
_praise you_

**Comment by BenGitsCode** [comment]
This should definitely be added. I know navigating to the option can be less-than-intuitive, especially for anyone not familiar with atom but the package is already installed, just disabled by default. A simple

``` bash
apm enable autosave
```

will do the trick a lot faster.

**Comment by BenGitsCode** [comment]
@jrhorn424 I made a pull request adding the autosave enablement [here](https://github.com/ga-wdi-boston/orientation/pull/171)

This can be closed.

**Comment by jrhorn424** [comment]
This can't be closed until the PR is merged. Thanks @BenGitsCode

**Comment by gaand** [comment]
Merged in 6a2874aff577ded1cf96c37601194ee478c8a87c

**Comment by jrhorn424** [comment]
`apm enable autosave` is insufficient, but necessary.

You also **must** enable the plugin inside its own options menu. It's stupid, I know.

<img width="1280" alt="settings" src="https://cloud.githubusercontent.com/assets/388761/21697829/41986714-d362-11e6-87ac-f0c42eac72e0.png">

<img width="1280" alt="settings" src="https://cloud.githubusercontent.com/assets/388761/21697838/47338b72-d362-11e6-9106-4a5f476945ca.png">
