### ISSUE TITLE
Add Linebreak to prompt in .bashrc

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/orientation#162]
After `git branch` and before `$` add `\n` for a new line. That way devs (and me) aren't getting commands split between lines when the filepath is miles long.

**Comment by RealWeeks** [comment]
@payne-chris-r take a look at the changes in commit 4bb60449dc3f9ce9cf9704de2d9eff88e5271799. Does it meet?

**Comment by jrhorn424** [comment]
That commit is unrelated.
