### ISSUE TITLE
Remove npm from this line

### ISSUE THREAD

**Issue by RDegnen** [ga-wdi-boston/orientation#164]
`npm install -g npm jshint jsonlint grunt-cli remark-lint jscs bower ember`

The `npm`  after `-g` should be removed. At least it threw an error when I pasted that on Linux

**Comment by gaand** [comment]
If node was installed via nvm, then it should error and should be included.
Since we always want to install node via npm, I don't think this is an issue.

**Comment by RealWeeks** [comment]
@gaand close this?

**Comment by gaand** [comment]
Duplicate (or vice versa) of #176.  Since that contains the appropriate correction, closing this one.
