### ISSUE TITLE
language-ember-htmlbars should be added to installfest

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/orientation#165]
Add `language-ember-htmlbars` to apm package list for ember syntax highlighting.

**Comment by RealWeeks** [comment]
@BenGitsCode updated in commit 6949ef4 @gaand do we live with the bug or should I revert the update?

https://github.com/jmurphyau/language-ember-htmlbars/issues/8

**Comment by gaand** [comment]
If/when we have cycles, we should investigate other providers of the functionality.

**Comment by gaand** [comment]
Maybe use this instead

https://atom.io/packages/atom-handlebars

:question: 

It seems to work correctly.

**Comment by gaand** [comment]
Well, it highlights and does comments correctly.

**Comment by jrhorn424** [comment]
I think I prefer `atom-handlebars` to `language-ember-htmlbars`, since the latter fubars commenting and requires being disabled early in the course lest it mess up html documents.

**Comment by gaand** [comment]
We should see if this fix is what's needed https://github.com/jmurphyau/language-ember-htmlbars/pull/8

**Comment by BenGitsCode** [comment]
☝That fix is working for me.

**Comment by gaand** [comment]
I have tested this in atom on OSX and Linux and it works.

**Comment by gaand** [comment]
If atom-handlebars worked correctly for me (completion), I might prefer it, but it doesn't, so I don't.

**Comment by jrhorn424** [comment]
This is currently present on master.
