### ISSUE TITLE
OSX Sierra?

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/orientation#167]
I assume we're not asking students to install OSX Sierra (the latest version) yet? It seems like a pretty good and non-breaking upgrade, but I'm inclined to wait a little bit since it's so new.

**Comment by gaand** [comment]
This is an open question to be decided by the instructional staff (this now included you :smile: ).

@jrhorn424 Upgraded and apparently isn't suffering.  If we decide we want them to upgrade, we should ask for that before they show up or do it at the start of Friday so their machines are ready by install fest.

**Comment by raq929** [comment]
I'm torn on this one, because I'd prefer to wait until version 10.12.1
comes out, at least, so that immediately obvious bugs are fixed.
On the other hand, some people have likely changed over already, and then
we have a cohort using two different versions.
This is not an upgrade that contains breaking changes, and upgrading
everyone would likely be fine.
In conclusion, I don't have strong opinions about this.

**Comment by gaand** [comment]
I'm in the process of upgrading now. If I run into problems, we should probably hold off. If not, we can probably go forward.

**Comment by RealWeeks** [comment]
@ga-wdi-boston/core Upgrading to OSX Sierra!

**Comment by RealWeeks** [comment]
@raq929 @gaand updated in commit bbc82ef okay to close?

**Comment by BenGitsCode** [comment]
I've upgraded as well and did a dry run of installfest last night, to make sure I was up to date with everything—no wdi-related issues so far.
