### ISSUE TITLE
Do we need to insert `/usr/local/bin` twice? 

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/orientation#168]
```
3.Execute the follow commands at the terminal:

echo 'export PATH=/usr/local/bin:$PATH' >> ~/.bash_profile
echo 'test -f ~/.bashrc && source ~/.bashrc' >> ~/.bash_profile

4.You will also need to update /etc/paths by running the following commands:

echo '/\/usr\/local\/bin/\nd\nwq' | sudo ed /etc/paths
echo '1i\n/usr/local/bin\n.\nwq' | sudo ed /etc/paths
```

I'm wondering why we're doing this. After running these commands, when I type `echo $PATH` I get `/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`. Presumably the first `/usr/local/bin` is being inserted by `.bash_profile` and the second by `/etc/paths`. Is there are reason we need both? 

It seems like we could take it out of `.bash_profile` and just leave it in `/etc/paths`.

**Comment by raq929** [comment]
My discussion of this with @smammy let to PR #169

**Comment by gaand** [comment]
@raq929 The answer to your initial question is a definitive "No".

I haven't reviewed the pull request in detail, but I wouldn't be surprised if some of the suggested changes are reasonable.

**Comment by RealWeeks** [comment]
@gaand @raq929 Thanks for the clean up, merged

**Comment by RealWeeks** [comment]
@gaand apologies. I already merged everything looked good upon review.
