### ISSUE TITLE
Before typing `rbenv install ...` in terminal 

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/orientation#178]
Per @gaand 
Before typing rbenv in terminal type `rbenv --version`

**Comment by gaand** [comment]
I think this should be titled "Before typing `rbenv install` ...".

**Comment by jrhorn424** [comment]
Agreed.

**Comment by MicFin** [comment]
@raq929 is this the section of the README you are speaking of?  Where would you like them to run `rbenv --version`? Or would you like the `rbenv version` on the last line to read `rbenv --version` 

> 
> 6.Install version 2.3.1 of Ruby and make it the system-wide default using the
> command:
> 
> ```bash
> rbenv install 2.3.1
> rbenv global 2.3.1
> ```
> You can see what versions of Ruby rbenv has downloaded by running
> `rbenv versions`; to see which version you are currently using, type either
> `rbenv version` or `ruby -v`.
> 
>
