### ISSUE TITLE
Use LinuxBrew for Ubuntu

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/orientation#180]
The only nonfunctional part I've seen so far is `brew services`.

For that, and other small differences, we'll likely need to create some linux only scripts.

**Comment by gaand** [comment]
Related to #62, #29.

**Comment by gaand** [comment]
We'll need to figure out the other parts that don't work as we do this again.

**Comment by raq929** [comment]
We used this in 016 and the only thing that we decided to have different instructions for was postgres. Can we close this?

**Comment by jrhorn424** [comment]
I'll close this. We've got instructions scattered across the README, though. See #228
