### ISSUE TITLE
Ensure developers have set break on exception in Chrome debugger. 

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/orientation#183]
Demonstrate and discuss. 

If it's not set, then we can't help.

**Comment by raq929** [comment]
I think I understand what you're trying to say, but I also suspect some autocorrect happened in the title.

**Comment by gaand** [comment]
Title corrected.  I created the issue on my iPhone and you can't edit titles in the mobile interface.

**Comment by jrhorn424** [comment]
@MicFin Please add the following with instructions:

<img width="714" alt="apps" src="https://cloud.githubusercontent.com/assets/388761/21653713/7a79bce6-d280-11e6-9d6a-4fa5360c7cd4.png">
