### ISSUE TITLE
combine apm commands into one liner 

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/orientation#185]
`apm aligner aligner-scss aligner-css`

**Comment by jrhorn424** [comment]
I believe the current section on `apm` is appropriate. @ga-wdi-boston/core Can anyone confirm whether or not this can be closed?

**Comment by BenGitsCode** [comment]
@jrhorn424 The current state looks appropriate to me. There was an issue in 015, that is no longer present, with the order of the commands.
