### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by Moumita-Mandal** [ga-wdi-boston/orientation#186]
getting error when I run npm install , so as per other comments ran npm install -g npm or npm install -g jshint  which ended successfully with the tree structure coming at the end. but then again npm start fails. So please advise. 

C:\Users\z013j29\Desktop\Angular2-GettingStarted-master\Angular2-GettingStarted
master\APM>npm install

> product-management@1.0.0 postinstall C:\Users\z013j29\Desktop\Angular2-Gettin
Started-master\Angular2-GettingStarted-master\APM
> typings install

typings ERR! message Unable to connect to "https://api.typings.org/entries/dt/n
de/tags/6.0.0%2B20160831021119"
typings ERR! caused by self signed certificate in certificate chain
typings ERR!
typings ERR! cwd C:\Users\z013j29\Desktop\Angular2-GettingStarted-master\Angula
2-GettingStarted-master\APM
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\z013j29\
Desktop\\Angular2-GettingStarted-master\\Angular2-GettingStarted-master\\APM\\n
de_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v7.0.0
typings ERR! typings -v 1.5.0
typings ERR! code EUNAVAILABLE
typings ERR!
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\c
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64
})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\z013j29\\AppDat
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! product-management@1.0.0 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the product-management@1.0.0 postinstall script 'typings ins
all'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the product-management p
ckage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs product-management
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls product-management
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\z013j29\Desktop\Angular2-GettingStarted-master\Angular2-G
ttingStarted-master\APM\npm-debug.log

**Comment by jrhorn424** [comment]
We do not support Windows in our WDI educational programs. Please seek support from your Android instructor. Thanks for filing!
