### ISSUE TITLE
Remove `ember` from `npm install -g ...` list

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#187]
Perhaps `npm install -g ... ember-cli` was meant instead.

`ember` shouldn't be installed globally.

**Comment by gaand** [comment]
I think I'd prefer to move toward #181 since versions are a moving target.  For instance, we need to talk about node LTS.

**Comment by jrhorn424** [comment]
@MicFin Please remove `ember` from the `npm install -g ...` list. Do not replace it per @gaand's comment.
