### ISSUE TITLE
Does this line always break the first time?

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/orientation#189]
Does the massive one-liner always break the first time? Is it 'cause `npm` isn't installed yet?
`npm install -g npm jshint jsonlint...`
Do we need to just run `npm install -g npm` 
and THEN
`npm install -g jshint jsonlint grunt-cli remark-lint jscs bower ember phantomjs-prebuilt`

**Comment by payne-chris-r** [comment]
Output from the massive one-liner: <img width="1250" alt="screen shot 2016-11-16 at 9 29 15 am" src="https://cloud.githubusercontent.com/assets/12667121/20351030/3184932a-abdf-11e6-973c-2277f46fbf8e.png">

**Comment by gaand** [comment]
@payne-chris-r I'm pretty sure an issue was recorded for this already.

Yes.  `npm install --global npm` first, then the rest.

**Comment by jrhorn424** [comment]
@MicFin Please see @gaand's comment above. This needs to be fixed in the README.

**Comment by jrhorn424** [comment]
#164 and #176 are duplicates. Closing them in favor of this issue.
