### ISSUE TITLE
Adjust formatting

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#2]
Use consistent whitespace and indentation for nesting list items and code examples.

**Comment by jrhorn424** [comment]
Using remark-lint should help. We can grab and share the `.remarkrc` from ga-wdi-boston/instructors.wiki

**Comment by RealWeeks** [comment]
WIP

**Comment by RealWeeks** [comment]
Added and fixed, sometimes styles ignored for aesthetic reasons.
