### ISSUE TITLE
Add instructions to xcode-select instructions

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#201]
After `xcode-select --install`, take a screenshot to indicate which dialog button developers should click (Install, not download Xcode).

**Comment by raq929** [comment]
http://cdn.osxdaily.com/wp-content/uploads/2014/02/confirm-install-command-line-tools-mac-os-x.jpg

**Comment by jrhorn424** [comment]
Here it is:

<img width="449" alt="cdn_osxdaily_com_wp-content_uploads_2014_02_confirm-install-command-line-tools-mac-os-x_jpg" src="https://cloud.githubusercontent.com/assets/388761/23191483/da2ed6c4-f86b-11e6-8f8c-df842736b899.png">

Edit alt text and width as appropriate:

```
<img width="449" alt="cdn_osxdaily_com_wp-content_uploads_2014_02_confirm-install-command-line-tools-mac-os-x_jpg" src="https://cloud.githubusercontent.com/assets/388761/23191483/da2ed6c4-f86b-11e6-8f8c-df842736b899.png">
```
