### ISSUE TITLE
Clarify instructions and add expected output for ed commands

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#202]
Mention that each should be typed separately, and add expected output.

```
echo '/\/usr\/local\/bin/\nd\nwq' | sudo ed /etc/paths
echo '1i\n/usr/local/bin\n.\nwq' | sudo ed /etc/paths
```

Should expect:

```
$ echo '/\/usr\/local\/bin/\nd\nwq' | sudo ed /etc/paths

45
/usr/local/bin
30

$ echo '1i\n/usr/local/bin\n.\nwq' | sudo ed /etc/paths

30
45
```

**Comment by gaand** [comment]
I believe this step is no longer necessary.  I thought I'd opened an issue for it.

**Comment by raq929** [comment]
@gaand Is this #182? If so, can you add clarification? If not, can you say more here?

**Comment by raq929** [comment]
Yes, #182 is the issue.
@jrhorn424 says there might also be an issue with Finder that requires these paths.
@gaand wants to know what else uses `etc/paths/`

@jrhorn424 will do some research in this regard.

**Comment by raq929** [comment]
http://apple.stackexchange.com/questions/215697/what-is-the-default-content-in-private-etc-paths

**Comment by jrhorn424** [comment]
Closing in favor of #182, which obsolesces this issue.
