### ISSUE TITLE
Possible terminal prompt mistake from code in .bashrc

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/orientation#208]
When setting up Git in `~/.bashrc`, the terminal prompt has an extra space and renders oddly. Not sure if intended but possible fix would be

```sh
# Git
function parse_git_branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "("${ref#refs/heads/}")"
}
export PS1="\w \$(parse_git_branch)\n\$ "
export EDITOR='atom --wait'
export VISUAL='atom --wait'
```

TO 
```sh
# Git
function parse_git_branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "("${ref#refs/heads/}")"
}
export PS1="\w \$(parse_git_branch)\$ "
export EDITOR='atom --wait'
export VISUAL='atom --wait'
```

**Comment by jrhorn424** [comment]
This was changed due to https://github.com/ga-wdi-boston/orientation/issues/162

This issue was what caused rendering issues in terminal with `CTRL + R` and `CTRL + P`.

**Comment by jrhorn424** [comment]
>  and renders oddly

Can you explain what you mean?

**Comment by raq929** [comment]
Closed unless it comes up again. Per @jrhorn424
