### ISSUE TITLE
Are we using any hub features?

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/orientation#225]
Because I don't see why we install it if we're not using it, and as far as I can tell we're not.

**Comment by gaand** [comment]
Do you have `hub` installed?  If not, how do you know.  If so, how do you know?

**Comment by raq929** [comment]
From looking at https://hub.github.com/, I see it give us a lot of shortcuts, but we don't use them in our repos.

**Comment by raq929** [comment]
Upon further discussion with @gaand - We are using tab completion for branches and possibly for files after `--`. 
I'm going to investigate on my machine tomorrow, which has hub but does not have these features to see if a step was missed in `hub` installation here. (I followed these installation steps before 015).

**Comment by jrhorn424** [comment]
A good place to use `hub create` would be after renaming a template repository and creating a history, since we've gotten a request to explicitly mention creating a remote.

```
# create a repo for a new project
$ git init
$ git add . && git commit -m "It begins."
$ git create -d "My new thing"
→ (creates a new project on GitHub with the name of current directory)
$ git push origin master
```

**Comment by jrhorn424** [comment]
If we're not using it much, I think we should use it more. To that end, we could use this shortcut for cloning repos, instead of giving them the opportunity to copy/paste the HTTP link. :wink:

```
# clone another project
$ git clone github/hub
→ git clone git://github.com/github/hub.git
```

**Comment by jrhorn424** [comment]
```
# open a pull request for the topic branch you've just pushed
$ git pull-request
```

**Comment by raq929** [comment]
I'm satisfied that we should install it and have opened an issue on meta for further discussion of how to incorporate it in our materials.
