### ISSUE TITLE
Linux brew instructions are not in the right place?

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#228]
They need to be here: https://github.com/ga-wdi-boston/orientation/blob/c77e4dd787838cf2d32a1c9ea9909347fd9cc4a0/INSTALLFEST.md#install-homebrew

But are here: https://github.com/ga-wdi-boston/orientation/blob/c77e4dd787838cf2d32a1c9ea9909347fd9cc4a0/INSTALLFEST.md#linux-only-1

Also, is this correct, homebrew installs on both linux and OSX?
```
# OSX and LINUX
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by jrhorn424** [comment]
Urgent? cc @payne-chris-r

**Comment by scottyscripts** [comment]
moved to and close on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/228
