### ISSUE TITLE
"OSX" is wrong. "OS X" is wrong. It's called "macOS" now.

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#229]
OS 9 became OS X became macOS

**Comment by jrhorn424** [comment]
This has been history of non-semantic versioning of apple's OS. We hope you enjoyed the program.

In seriousness, please replace references to both "OSX", "OS X", and possibly "mac". Use "macOS" instead.

**Comment by jrhorn424** [comment]
If you like, we can keep a note about googling with `("OS X" or "macOS")`.

**Comment by scottyscripts** [comment]
moved to and closed on https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/229
