### ISSUE TITLE
Confirm whether `hub` alone adds bash completion, or if `brew bash-completion` is needed

### ISSUE THREAD

**Issue by MicFin** [ga-wdi-boston/orientation#231]
Seems like consultants generally have this set up on their own computers.  
It enables a developer to use `tab` to complete the name of a branch.

https://stackoverflow.com/questions/12399002/how-to-configure-git-bash-command-line-completion

**Comment by raq929** [comment]
I believe `hub` is supposed to do this for us, but it's currently not configured correctly to do so.

**Comment by jrhorn424** [comment]
I'd like to see this added.

@BenGitsCode Did you confirm or deny that `hub` takes care of this?

**Comment by jrhorn424** [comment]
Dang it @raq929 too fast!

**Comment by BenGitsCode** [comment]
Yup @raq929  is right, I believe it can be configured to do so but isn't currently.

**Comment by raq929** [comment]
Can you post directions for configuration here, plz?

**Comment by BenGitsCode** [comment]
I'm not entirely sure how to use it in hub, but I'm not testing what I'm seeing on my machine. 

without hub and using brew, this strikes me as the easiest option. https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion#os-x--macos

**Comment by raq929** [comment]
That's not `hub` at all. But OK. Sounds fine.

**Comment by MicFin** [comment]
`hub` bash completion looks slightly more involved but I did not try it. I did succeed at the steps @BenGitsCode shared above rather easily.

https://github.com/github/hub#shell-tab-completion
https://github.com/github/hub/blob/master/etc/hub.bash_completion.sh

**Comment by jrhorn424** [comment]
I've read the linked script. Thanks @MicFin.

It looks like as long as `hub` is configured correctly, it should provide completion by default.

I'd like that confirmed manually.

**Comment by scottyscripts** [comment]
moved to and closed on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/231
