### ISSUE TITLE
Update node version

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/orientation#233]
We updated what we're installing but not what we say we're installing. I suggest taking the version number off the template.

```diff
- Use NVM to install the latest longterm stable version of Node (4.4.7)
+ Use NVM to install the latest longterm stable version of Node
```

**Comment by gaand** [comment]
Version number off, yes.

code name, maybe (e.g. lts/argon, lts/boron, etc)?

**Comment by jrhorn424** [comment]
Obsolesced as of dc3ae1992ba409e55a44c415fab0554f326d1c2f
