### ISSUE TITLE
Need eslint apm package, not jshint

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/orientation#234]
We install jshint linter in the apm package, we need to remove it in favor of eslint (and maybe eslint-standard?)

**Comment by gaand** [comment]
Just `linter-eslint`.  Our templates include the stuff about standard.

**Comment by scottyscripts** [comment]
jshint linter replaced with eslint linter

**Comment by jrhorn424** [comment]
See #249
