### ISSUE TITLE
nvm install boron command does not work in every environment

### ISSUE THREAD

**Issue by MicFin** [ga-wdi-boston/orientation#235]
`nvm install --lts=boron` errors in some environments.

```
grep: unrecognized option `--lts=boron'
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
grep: unrecognized option `--lts=boron'
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
Version '--lts=boron' not found - try `nvm ls-remote` to browse available versions.
```

The solution we used was to install the version number specifically `nvm install 6.9.4`.  We did not spend adequate time investigating what environment settings may have caused this error.

**Comment by payne-chris-r** [comment]
`nvm install lts/boron`

**Comment by gaand** [comment]
@payne-chris-r is that the solution?

**Comment by MicFin** [comment]
`nvm install lts/boron` did not work for the scenario we ran into with @jordanallain's set up.  
We tried `nvm install lts/boron` and `nvm install --lts=boron` which both errored
and had to run `nvm install 6.9.4` for it to work.

**Comment by payne-chris-r** [comment]
Most people that one of these didn't work for are getting `nvm: command not found.` Those people didn't follow directions and skipped the last step. They should be 🔨d

**Comment by MicFin** [comment]
`nvm install --lts=boron` worked for every developer during `017` installfest

...unless Monday proves otherwise :)

**Comment by scottyscripts** [comment]
if --lts=boron option doesn't work, it will install based on version number with the new scripts.

**Comment by jrhorn424** [comment]
@sdavidson140 Those version numbers are a little out of date. Latest boron has advanced.

**Comment by scottyscripts** [comment]
moved to and closed on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/235
