### ISSUE TITLE
nvm command not found

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/orientation#236]
If devs are getting `nvm: command not found` or something along those lines it's likely because they didn't copy pasta the piece before it, and instead ran it in their terminal...

**Comment by danman01** [comment]
Yea, they forgot / missed the instruction to set up their nvm executable or path from a previous copy / paste section. In the installfest text, there are many instances of a line of text instruction saying: 

type this in the command line `atom ~/.bashrc` and then paste the following:

```
some code to paste here
```
And it seemed more often than not that instruction to open up .bashrc in atom was skipped by developers, and instead `some code to paste here` was just put in the terminal, which does nothing.

Maybe we could look into the various places the developers will be entering text, and have some sort of color / symbol that refers to the specific instruction, like:

:penguin: this is entered on the command line 

:green_book: this is entered within atom / text editor 

And some more symbols to highlight important steps:

:floppy_disk: don't forget to save

:volcano: completely close out and reopen your shell

**Comment by scottyscripts** [comment]
moved to and closed on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/236
