### ISSUE TITLE
Admin user setup

### ISSUE THREAD

**Issue by danman01** [ga-wdi-boston/orientation#237]
We noticed today in lm01 that students needed to adjust their user accounts to be admin users. After doing that, they were in the sudoers file and could do the installfest tasks. Might be worth mentioning near the top to make sure we are working with an admin level user.

Another instance of needing sudo was when we `chown`ed a directory. We needed to append `sudo` to get our `admin` user to own `/usr/local`:

`chown -R $(whoami):admin /usr/local`

should be:

`sudo chown -R $(whoami):admin /usr/local`

**Comment by jrhorn424** [comment]
Addressed as of (or before) 3986aadf130b7608ebf50d970370397013985293.

@sdavidson140 Next time, drop a commit hash, or mention the issue number in your commit.
