### ISSUE TITLE
Mention example files that are in orientation folder

### ISSUE THREAD

**Issue by danman01** [ga-wdi-boston/orientation#239]
As a reference while going through installfest, developers can look at the [orientation folders'](https://github.com/ga-wdi-boston/orientation) example `.bashrc` and `.bash_profile`. This could be mentioned near the top and / or bottom of the installfest doc so that developers can ensure they've done everything correctly.

**Comment by MicFin** [comment]
Unfortunately the example `.bashrc` is not up to date.  It should be checked against the current steps in installfest.  I did not check the `.bash_profile` but it should likely be reviewed first too.

**Comment by danman01** [comment]
This is the diff I see after browsing the steps in the INSTALLFEST.md.

If the example `.bashrc` and `.bash_profile` are worth updating, which I think they are, I can add these and submit a PR:

```sh
# hub
eval "$(hub alias -s)"

# Rbenv, before the git section
if which rbenv > /dev/null; then
 eval "$(rbenv init -)"
fi
```

**Comment by jrhorn424** [comment]
@sdavidson140 Why wasn't this addressed?

**Comment by jrhorn424** [comment]
@danman01 A PR would be appreciated.

**Comment by scottyscripts** [comment]
@jrhorn424 The hub.sh script adds `eval "$(hub alias -s)"` to .bashrc

The rbenv script adds `if which rbenv > /dev/null; then
 eval "$(rbenv init -)"
fi`
to .bashrc

**Comment by scottyscripts** [comment]
@jrhorn424 I don't know if it makes sense to have the examples anymore since we can be sure these steps are working in scripts.

**Comment by jrhorn424** [comment]
> The rbenv script adds if which rbenv > /dev/null; then eval "$(rbenv init -)" fi
to .bashrc

@sdavidson140 Then find me a commit SHA.

**Comment by jrhorn424** [comment]
> I don't know if it makes sense to have the examples anymore since we can be sure these steps are working in scripts.

Open an issue for removal. Recommend whatever example files should be removed as you see fit.

**Comment by scottyscripts** [comment]
Moved to and closed on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/239
