### ISSUE TITLE
Use environment variable for rbenv install

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/orientation#241]
```diff
- echo bundler > ~/.rbenv/default-gems
+ echo bundler > ${RBENV_ROOT}/default-gems
```

**Comment by payne-chris-r** [comment]
Is this something we need to be concerned about LM01 not having done correctly that will be a problem come `ruby` lessons?

**Comment by gaand** [comment]
@payne-chris-r Unlikely (so, no).

Doing this everywhere would allow us to be explicit and consistent.  But, we might want to leave it the way it is and let those who rely on `RBENV_ROOT` suffer.

**Comment by scottyscripts** [comment]
moved to and closed on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/241
