### ISSUE TITLE
Remove headings that say `<OS> ONLY`

### ISSUE THREAD

**Issue by danman01** [ga-wdi-boston/orientation#245]
This is unclear at times due to Mac OSX / Linux Only header size and / or indenting of sections underneath the headers.

We could:
- clean up the header size and indenting
- and / or:
    We could have a distinct symbol for linux only or mac only, and for everything else it could be assumed we run on all systems.
- or:  
     We could separate the INSTALLFEST.md into two files, one for linux and one for mac.

**Comment by raq929** [comment]
We've considered the third option, and decided it doesn't make a whole lot of sense since a lot of the instructions are the same. 

I like the idea of using symbols. 🐧  for linux? 😛  
⛰  for mac? (That won't actually work, 'cause Sierra will go away.)
Cleaning up the headers and indenting is also a good idea.

**Comment by raq929** [comment]
Related to #147

**Comment by MicFin** [comment]
Another example, this large **Linux ONLY** heading is misleading since it includes steps for `OSX and LINUX` directly beneath it.

> ### Linux ONLY
> 
> Rbenv on Linux depends on another library called `libffi-dev`. Download and
> install it with the following command.
> 
> ```bash
> # LINUX ONLY
> sudo apt-get install libffi-dev
> ```
> 
> 1.  Install Rbenv
> 
>     ```bash
>     # OSX and LINUX
>     brew install rbenv
>     ```
> 1.  Configure rbenv to use the correct directories:
> 
>     `atom ~/.bashrc` and paste in the following code **BEFORE** the stuff you pasted
>     in about Git.
> 
>     ```bash
>     # OSX and LINUX
>     # Rbenv
>     if which rbenv > /dev/null; then
>      eval "$(rbenv init -)"
>     fi
>     ```

https://github.com/ga-wdi-boston/orientation/blob/master/INSTALLFEST.md#linux-only-2

**Comment by jrhorn424** [comment]
If there are no more specific fixes mentioned, I'd like to close this issue. It is too unfocused. Individual confusions should be noted in separate issues.

Please remove headings that say `<OS> ONLY` since that information should be noted inside a fenced code block as a comment.

**Comment by scottyscripts** [comment]
Issue no longer relevant with new structure of installfest on GHE
