### ISSUE TITLE
Add sjs snippets to atom during installfest

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/orientation#248]
https://atom.io/packages/standardjs-snippets or similar

**Comment by raq929** [comment]
Related #115?

**Comment by scottyscripts** [comment]
standardjs-snippets added to installfest

**Comment by jrhorn424** [comment]
Does this conflict with the intent of #254?

**Comment by scottyscripts** [comment]
moved to and closed on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/248
