### ISSUE TITLE
Remove jshint and jscs from installfest

### ISSUE THREAD

**Issue by MicFin** [ga-wdi-boston/orientation#249]
Remove jshint
```diff
 # OSX and LINUX
-  apm install aligner-ruby atom-beautify linter-jshint editorconfig \
+ apm install aligner-ruby atom-beautify editorconfig \
  esformatter fixmyjs git-diff-details git-history git-plus language-markdown \
  less-than-slash linter linter-csslint linter-eslint linter-markdown \
  linter-rubocop linter-ruby linter-scss-lint linter-tidy markdown-writer \
  sort-lines language-ember-htmlbars
```
https://github.com/ga-wdi-boston/orientation/blob/master/INSTALLFEST.md#atom-add-ons

Remove jscs
```diff
# OSX and LINUX
npm install --global npm
- npm install --global jshint jsonlint grunt-cli remark-lint jscs bower phantomjs-prebuilt
+ npm install --global jshint jsonlint grunt-cli remark-lint bower phantomjs-prebuilt
```
https://github.com/ga-wdi-boston/orientation/blob/master/INSTALLFEST.md#installing-nvm-and-nodenpm

**Comment by MicFin** [comment]
Atom prompted some developers to install the following dependencies.
`linter-ui-default`
`busy-signal, intentions`

**Comment by MicFin** [comment]
Also so https://github.com/ga-wdi-boston/orientation/issues/234 and https://github.com/ga-wdi-boston/orientation/issues/238

**Comment by scottyscripts** [comment]
jshint removed from npm install and apm install. other atom packages added

**Comment by jrhorn424** [comment]
@sdavidson140 Next time, drop a commit hash, or mention the issue number in your commit. Please review the PR process on the wiki.

0541e5755d4e150b7bb470f22815758c019fb691
