### ISSUE TITLE
Fix linter-scss-lint

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/orientation#250]
`gem install scss_lint`

@ga-wdi-boston/core Someone took this out by mistake.

Alternatively, perhaps preferably, install this atom package instead `linter-sass-lint`

**Comment by scottyscripts** [comment]
atom package installed

**Comment by jrhorn424** [comment]
@sdavidson140 Next time, drop a commit hash, or mention the issue number in your commit. Please review the PR process on the wiki.

10a8f9536581cca96be97434810307fac2b9d1f1
