### ISSUE TITLE
Install standardjs snippets? formatter?

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#251]
- https://atom.io/packages/standardjs-snippets
- https://atom.io/packages/standard-formatter

**Comment by jordanallain** [comment]
install `linter-ui-default`
depends on `intentions` and `busy-signal`

**Comment by gaand** [comment]
How does this relate to #254 :question:

**Comment by scottyscripts** [comment]
moved to and closed on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/251
