### ISSUE TITLE
Disable autocomplete snippets

### ISSUE THREAD

**Issue by MicFin** [ga-wdi-boston/orientation#254]
Disable autocomplete snippets because they are often incorrect best practices and do not help developers build muscle memory.  Add a step to installfest for disabling snippets.

https://github.com/atom/snippets/issues/55

**Comment by gaand** [comment]
```sh
apm disable autocomplete-snippets
```

**Comment by scottyscripts** [comment]
This has been added to the most recent version of installfest automated scripts in `orientation/config/atom.sh`

**Comment by jrhorn424** [comment]
@sdavidson140 Next time, drop a commit hash, or mention the issue number in your commit. Please review the PR process on the wiki.

10a8f9536581cca96be97434810307fac2b9d1f1
