### ISSUE TITLE
Remove example .bashrc and .bash_profile from repo

### ISSUE THREAD

**Issue by scottyscripts** [ga-wdi-boston/orientation#257]
I don't think that it makes sense to have these example files anymore now that the scripts are automated and we can be sure that these files will look as expected.

**Comment by BenGitsCode** [comment]
It may be worth having an example for our reference but may fit better into a wiki or something.

**Comment by scottyscripts** [comment]
Closing this outdated issue. This has been addressed and resolved on GHE
