### ISSUE TITLE
Add lunchy to start services from command line

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#4]
https://rubygems.org/gems/lunchy/versions/0.10.3

**Comment by jrhorn424** [comment]
After linking launch services scripts (for example, the one mentioned in `brew info postgres`), it can be convenient to choose when to start and stop services. `lunchy start postgres` is easy to remember. Also, `lunchy ls` lists all available services and `lunchy status` lists "enabled" services and their PIDs. Pretty convenient.

**Comment by RealWeeks** [comment]
Opted for brew services instead

**Comment by jrhorn424** [comment]
I'd like to discuss this more.

**Comment by jrhorn424** [comment]
I'd like to throw my support behind brew services. It has an additional cleanup feature which is nice.

We'll make use of things like this all the time: `brew services start postgres`
