### ISSUE TITLE
Versions for cohort 010

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#41]
I suggest the following versions of major software for this cohort:
- Latest stable atom (evergreen)
- Latest stable Chrome (evergreen)
- ruby 2.2.4
- node 4.2.4
- latest npm for this version of node

Note that previous versions of node and ruby installed with version managers might need to be deleted. For example, npm installed with node v5.0.0 doesn't work with node v4.2.2. I don't know why, I just know it causes issues.

Anything I've missed? Any arguments for different versions? @ga-wdi-boston/core need feedback soonish. Thanks.

**Comment by GA-MEB** [comment]
That all sounds fine to me. I definitely remember the NPM issue you've described.

**Comment by jrhorn424** [comment]
Please document this. @MattB-GA-Boston @J-Weeks please self-assign.

**Comment by RealWeeks** [comment]
Atom 1.4 good,
Chrome 47.0.2526 good,
updated ruby to 2.2.4,
updated node to  4.2.4 
NVM updated

**Comment by jrhorn424** [comment]
Thanks @J-Weeks
