### ISSUE TITLE
Document example classroom culture results

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#48]

**Comment by RealWeeks** [comment]
Break into groups talk about culture, what you want, write wall of culture

**Comment by jrhorn424** [comment]
This is the wrong label.

**Comment by berziiii** [comment]
@jrhorn424 okay to rename to 'Workspace Culture'?

From @J-Weeks comment, identify themes and typical categories align around:
- Be respectful and you'll receive respect
- Be open to communicate as well as giving AND receiving feedback
- Be respectful to others abilities while fostering a collaborative environment
- Keep a growth mindset
- Leave baggage and ego at the door
- Have Fun
- This is an open and safe space

**Comment by jrhorn424** [comment]
Good stuff. Here's some historical culture walls:

![img_1325](https://cloud.githubusercontent.com/assets/388761/15190946/73c310d4-1780-11e6-8116-c312818232cf.jpg)

![img_1326](https://cloud.githubusercontent.com/assets/388761/15190953/781696b0-1780-11e6-9f16-859bc958883b.jpg)
