### ISSUE TITLE
Add optional script for bootstrapping new machines

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#5]
Sometimes students lose the use of their laptops during the course. Going through installfest on a new machine is time-consuming.

There are pedagogical reasons for going through installfest manually, and in a large group with heterogenous machines, there aren't large scaling advantages to automatically setting up development environments.

An automated script would be useful, but also additional maintenance. Tools like `ansible` also make the script useful as a "unit test" for infrastructure, since these provisioning tools also include checks for successful completion of tasks.

**Comment by jrhorn424** [comment]
@ga-wdi-boston/core This is a large change, but one I believe yields a large benefit. I also happen to hold strong opinions about this, and I love to discuss. Here's a [good read](http://dsg.tuwien.ac.at/staff/hummer/docs/2013-middleware-iac.pdf).

I'd like to work on this, and I'd like to have it done by cohort 012.

**Comment by jrhorn424** [comment]
I still believe this has value. Obviously, we've had other priorities on previous iterations. I'd love to hear others' opinions on this.

**Comment by gaand** [comment]
I'd love to have automated scripts for various bits. Most should work for both OSX/Linux. Possibly a driver script for the whole thing?

**Comment by scottyscripts** [comment]
ported to enterprise and closed https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/5
