### ISSUE TITLE
Document consultant panel questions

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#50]

**Comment by berziiii** [comment]
@jrhorn424, @payne-chris-r and @RDegnen let's try to document this for WDI-012

**Comment by RealWeeks** [comment]
@berziiii I tried to do this last time but it's difficult when you're on the panel yourself.

**Comment by jrhorn424** [comment]
- What do you believe is the key to success in this program?
- How did you being your career as a developer?
- What was your biggest challenge in starting your career?
- Can you describe your personality and communication style?
- What motivates you to teach?
