### ISSUE TITLE
Document schedule/order of orientation topics

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#51]
This should be done in addition to documenting the content of these topics. It will facilitate scheduling in the future.

@berziiii If you could type up a quick outline of your slides, that'd be perfect.

**Comment by berziiii** [comment]
Orientation runs from 9:00am to ~ 5:00pm
Orientation Agenda below:
- WDI Consultant Introductions(15min)
- Icebreaker (2 truths and a lie)(30min)
- Alumni Panel(30min
- Consultant Q&A(30min)
- Program Roadmap, Expectations & Policies(30min)
- Workspace Culture(30min)
- GA-Boston team introductions (15min)
- Lunch (1hr)
- Operations Presentation (15 min)
- Outcomes Presentation (15 min)
- Install-fest ( ~2+ hours)
- Orientation Celebration (Starts around 5:00pm-5:30pm)

**Comment by jrhorn424** [comment]
Looks great. I think this could go well as a "table of contents" at the top of the README.
