### ISSUE TITLE
Document alumni panel example questions

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#53]

**Comment by RealWeeks** [comment]
- What are your experience taking WDI?
- What as the most challenging thing for you during the cohort?
- What is something you wish you knew during your time at WDI?
- Is there something you heard but didn't really internalize that you wish you did?
- Open floor to questions.

**Comment by berziiii** [comment]
@jrhorn424 and @J-Weeks, where should we document these questions to keep consistency between cohort alumni panels? Wiki?

**Comment by RealWeeks** [comment]
@berziiii I defer to @jrhorn424

**Comment by jrhorn424** [comment]
- Introduction: Who are you? What did you do before? What did you think of the program? What do you do now?
- What do you wish someone had told you? Would you have believed it?
- How long was the gap between learning something and feeling comfortable using it?
- What is your learning process on-the-job?
- How important were the projects for your learning and comfort?
- What was it like day-to-day and week-to-week?
- How do you convince someone that you can do the job even though you don't have experience?
- What was your highest level of education? Does your degree matter?
