### ISSUE TITLE
Include example linter configuration files for each major technology

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#54]
These should also be included in project directories for easy editing. The advantage of distributing them during orientation is that sensible default configuration stored in the home directory can be found by most of the linters used.

**Comment by berziiii** [comment]
@jrhorn424 can you shed some light on if this has been implemented? Thanks.

**Comment by jrhorn424** [comment]
Absolutely. For each of the following repositories, take the configuration dot-files and add them to this repository. Then, add instructions in the README for placing copies of these files under the `$HOME` directory.
- **`node-template`**
- **`ruby-template`**
- `rails-template`
- `express-template`
- `ember-template`
- `js-template`

Templates in **bold** should win if there is conflict between identically-named files.

This will ensure that even when developers are working outside a template repository, they have some sensible linter configurations available.
