### ISSUE TITLE
Don't install npm on Linux.  Use nvm install script instead.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/orientation#57]
Remove instruction to `sudo apt-get install npm`

and replace with

``` sh
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash
```

See https://github.com/creationix/nvm#install-script

The version, `v0.30.1`, will change over time.

**Comment by RealWeeks** [comment]
added to orientation doc
