### ISSUE TITLE
Break this repository into individual knowledgebase wikis

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#59]
Then we can use the README to organize and link to the day's activities.

Knowledgebase here: https://github.com/ga-wdi-boston/meta/wiki

**Comment by jrhorn424** [comment]
I've changed my mind. We might revisit this in the future. It's a large and tedious change.

**Comment by raq929** [comment]
We were talking about ditching installfest at one point and having day-of smaller installs. This would be helpful for that.

**Comment by gaand** [comment]
I think I would prefer install guides (as repositories). See ga-wdi-boston/instructors#46

**Comment by jrhorn424** [comment]
> I think I would prefer install guides (as repositories). See ga-wdi-boston/instructors#46

Future discussion should take place at the above.
