### ISSUE TITLE
Incorrect config for setting Atom as Git editor

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/orientation#61]
Adding the following to the `.bashrc` file does not work.

```
export EDITOR='atom --wait'
```

**Comment by jrhorn424** [comment]
Works fine on my machine.

**Comment by jrhorn424** [comment]
You need both:

``` sh
export EDITOR='atom --wait'
export VISUAL='atom --wait'
```

Also, it's good to go ahead and do:

``` sh
git config --global core.editor "atom --wait"
```

**Comment by GA-MEB** [comment]
I think the latter is a sufficient fix - that seemed to work with the students who had problems today.

**Comment by jrhorn424** [comment]
Sure. But it won't help when other programs try to use VISUAL or EDITOR.

**Comment by RealWeeks** [comment]
added:

```
export EDITOR='atom --wait'
export VISUAL='atom --wait'
```

to orientation docs

**Comment by gaand** [comment]
@J-Weeks Is 

``` sh
git config --global core.editor "atom --wait"
```

in README.md?

**Comment by RealWeeks** [comment]
added @gaand

**Comment by gaand** [comment]
@J-Weeks Please don't close issue opened, or reopened by someone else.  @jrhorn424's comment didn't take it far enough in my view.  You should `@` the person who opened and ask them to confirm the close, with a commit specified if possible.  Closing issues shouldn't be rushed.

**Comment by berziiii** [comment]
@J-Weeks and @gaand, I can confirm that 

``` bash
git config --global core.editor "atom --wait"
```

is in README.md. Okay to close issue?

**Comment by jrhorn424** [comment]
LGTM. @gaand Please reopen if you have any other concerns.
