### ISSUE TITLE
Inconsistent formatting between NVM section and the others

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/orientation#63]
OS X / Linux split is handled differently.

**Comment by jrhorn424** [comment]
Could you elaborate a bit? Is this an issue with markdown formatting, with structure?

**Comment by GA-MEB** [comment]
Markdown formatting. In the NVM section, OS X and Linux directions are delineated by comments within the code snippets; in other parts of the document, they're delineated by headings.

**Comment by RealWeeks** [comment]
standardized formatting
