### ISSUE TITLE
For Linux users, make sure that PATH is defined above NVM configuration in ~/.bashrc

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/orientation#64]
Having this not be the case led students to need to re-define which version of node to use (`nvm use blah`) each time they opened a terminal.

**Comment by jrhorn424** [comment]
This is related to #11 and #25.

The advice in #25 only applies to Macs.

**Comment by berziiii** [comment]
@jrhorn424 Can I get your eyes to see if what is in README.md is correct:

1.Open your `.bashrc` file by typing `open .bashrc` and paste in the following:

#### OS X

``` bash
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
```

#### Linux

``` bash
export NVM_DIR="/home/your_username/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
```

**Comment by jrhorn424** [comment]
Better:

#### Linux

``` bash
export NVM_DIR="/home/$(whoami)/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
```

**Comment by berziiii** [comment]
see commit faeeeff. Let me know if we're okay to close issue. Thanks.

**Comment by jrhorn424** [comment]
Thanks @MattB-GA-Boston for reporting and @berziiii for fixing. Please mention this as closed in your PR.
