### ISSUE TITLE
Install latest git

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#65]
Use homebrew git instead of system git

**Comment by GA-MEB** [comment]
We already do this.

On Wed, Jan 20, 2016 at 11:48 AM, Jeffrey Horn notifications@github.com
wrote:

> Use homebrew git instead of system git
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-wdi-boston/orientation/issues/65.

## 

_Matt Brendzel_
_Developer In Residence_
General Assembly - Boston | 51 Melcher Street, Boston, MA 02210
matt.brendzel@generalassemb.ly | @mattbrendzel | @GA_Boston | (215) 839 9428
http://generalassemb.ly

Join the party. Sign up for the GA newsletter
https://generalassemb.ly/locations/boston/.

**Comment by jrhorn424** [comment]
Thanks! You're right. I'll close.

One student didn't have it.
