### ISSUE TITLE
When node v5 has stabilized and has LTS, we can start using the spread operator

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#71]
https://nodejs.org/en/docs/es6/#ref-2

So instead of 

``` js
let target = function(greeting, location) {
  return `${greeting} from ${location}`;
};

let wrapper = function() {
  return target.apply(this, arguments);
};
```

We can have

``` js
let target = function(greeting, location) {
  return `${greeting} from ${location}`;
};

let wrapper = function() {
  return target(...arguments);
};
```

**Comment by gaand** [comment]
@jrhorn424 transpiler support?

**Comment by jrhorn424** [comment]
Babel currently supports this. This is the preset we use, and spread is one of the "plugins": http://babeljs.io/docs/plugins/preset-es2015/

**Comment by berziiii** [comment]
@jrhorn424 and @gaand thoughts on this issue? Was a decision made or should we leave this open? Thanks.

**Comment by jrhorn424** [comment]
Node doesn't have an LTS release >= 5 yet

**Comment by gaand** [comment]
It appears they're going straight to 6 for LTS. https://github.com/nodejs/LTS#lts_schedule

**Comment by raq929** [comment]
Moved to `meta` as it is no longer relevant to orientation. @jrhorn424 approved this message.
