### ISSUE TITLE
create ${RBENV_ROOT}/default-gems after installing rbenv.

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/orientation#72]
Remove this:

Then download a package with a number of common gems.

brew install rbenv-default-gems

**Comment by jrhorn424** [comment]
Remove what?

**Comment by RealWeeks** [comment]
rbenv-default-gems

**Comment by RealWeeks** [comment]
instruction to install has been removed

**Comment by gaand** [comment]
@J-Weeks Why?  

Adding instructions to include some default gems in `$(rbenv root)/default-gems` makes more sense then removing this. 

For linux, the installation instructions [here](https://github.com/rbenv/rbenv-default-gems) seem straightforward.

**Comment by berziiii** [comment]
@jrhorn424, @gaand @J-Weeks, decision needed on if this issue is closed or not? There is currently nothing in README.md referencing `rbenv-default-gems`.

**Comment by jrhorn424** [comment]
@ga-wdi-boston/core I'm of the opinion that, since our dependencies are managed in each repository, there is little value added to including a set of default gems at install fest. The only one that makes sense to install with _every ruby version install_ (what rbenv-default-gems does) is bundler, and `gem install bundler` takes care of that.

**Comment by jrhorn424** [comment]
After speaking with @gaand and thinking about it more, I agree that we should add this back to the README. It's consistent with installing other default tools, even if it isn't strictly necessary.

It's worth noting that `node` style is to depend on globals, while `ruby` style is to depend on executables available within a project, using something like `bundle binstubs` or `bundle exec`.

**Comment by gaand** [comment]
I think the only required entry is `bundler`

**Comment by raq929** [comment]
So, I should include `gem install bundler` and nothing else, correct?

**Comment by payne-chris-r** [comment]
Yeah. That's what @gaand and I talked about last time. Everything else can be installed 'just in time' including rails. The first rails lesson (or practice) will take some time, but after that we should be fine.

**Comment by gaand** [comment]
@raq929 This file just needs to list bundler

```sh
 $ cat ~/.rbenv/default-gems 
# Use Gemfile to install gems
bundler
 $
```

**Comment by raq929** [comment]
1. Install rbenv
2. Create default gems & add bundler
3. Install ruby

**Comment by raq929** [comment]
`touch ~/.rbenv/default-gems `
`echo bundler < ~/.rbenv/default-gems`

.rbenv should be in root directory.

**Comment by gaand** [comment]
Please not corrections.

```diff
-touch ~/.rbenv/default-gems
-echo bundler < ~/.rbenv/default-gems
+echo bundler > ~/.rbenv/default-gems
```

```diff
-.rbenv should be in root directory.
+.rbenv should be in user's home directory.
```

**Comment by jrhorn424** [comment]
@gaand's corrections need to be addressed. Good spot re-opening this @payne-chris-r.

**Comment by payne-chris-r** [comment]
Should be resolved with last commit on `lm01/master` branch.
