### ISSUE TITLE
rbenv-gem-rehash is deprecated

### ISSUE THREAD

**Issue by laurenfazah** [ga-wdi-boston/orientation#76]
Step 3 of the Ruby install

**Comment by jrhorn424** [comment]
Does rbenv rehash on its own now?

**Comment by laurenfazah** [comment]
Looks like no. This is from the rbenv docs: 

> `rbenv rehash`
> 
> Installs shims for all Ruby executables known to rbenv (i.e., ~/.rbenv/versions/_/bin/_). Run this command after you install a new version of Ruby, or install a gem that provides commands.

[rbenv docs](https://github.com/rbenv/rbenv#rbenv-rehash)

**Comment by RealWeeks** [comment]
added to doc
