### ISSUE TITLE
Include grunt

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/orientation#88]
Include global grunt install to prevent having to do it later in the course.

**Comment by gaand** [comment]
`grunt-cli`

**Comment by berziiii** [comment]
@gaand & @J-Weeks, commit 4ed35e56f8cab3652a231f4b4d5c9c717f1e8963. It appeared that grunt-cli was already in the doc but the issue wasn't closed. I made a separate step for the install of grunt-cli to not confuse the students.

**Comment by berziiii** [comment]
see commit 4ed35e5

**Comment by RealWeeks** [comment]
@berziiii commit link?

**Comment by berziiii** [comment]
@J-Weeks 4ed35e5

**Comment by jrhorn424** [comment]
LGTM. Please reopen if needed.
