### ISSUE TITLE
Bug in `language-ember-htmlbars` Atom plugin

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/orientation#94]
`language-ember-htmlbars` overrides HTML comment syntax and replaces it with Handlebars/HTMLbars comment syntax on **all HTML files**. Currently, the only way to get around this is to disable (or uninstall) the extension.

An issue exists on the extension's github repo:
https://github.com/jmurphyau/language-ember-htmlbars/issues/8

**Comment by berziiii** [comment]
@jrhorn424 since there is an issue on the github repo for this plugin, and it doesn't appear to be resolved yet, should we remove it from installfest for this cohort?

**Comment by jrhorn424** [comment]
@berziiii This should still be tracked here. It isn't something we can fix now, but we should know about it each iteration.

As far as removing `language-ember-htmlbars`, I think it's safe to remove it for now. I had developers in the previous cohort disable it in the first unit, and re-enable it in the last unit, so removing reduces friction slightly. Developers will just install it later.

**Comment by raq929** [comment]
It looks like a fix has been merged on their end, should we add this back in?

**Comment by jrhorn424** [comment]
It has reappeared on its own? 🤔 

Closing since there's a fix upstream and installing the package is in the README.
