### ISSUE TITLE
Change js-linter

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/orientation#96]
@gaand uses one that is different (an better) than the one we have students install. Resolved some bugs during the class for some students by switching.  @gaand What linter do you use?

**Comment by jrhorn424** [comment]
@J-Weeks Do you mean inside Atom?

I use linter-eslint, which actually uses the jshint configuration if an eslint configuration isn't present.

**Comment by berziiii** [comment]
@ga-wdi-boston/core did we decide on which js-linter we want to include?

**Comment by gaand** [comment]
I use linter-jshint which did seem to work for some who had issues with linter-eslint

**Comment by jrhorn424** [comment]
@gaand I thought you had issues with `linter-jshint`, but I'm probably mis-remembering.

**Comment by gaand** [comment]
I've had issues with some parts of the linter subsystem from time-to-time, but the `linter-` package seem to update frequently.

**Comment by raq929** [comment]
Is this outdated because we're upgrading to `eslint`? If yes, is there an atom plugin for `eslint` that we need to add?

**Comment by raq929** [comment]
Nevermind, we're already installing the atom plugin.
The remaining question is is this issue outdated and able to be closed?
If no, what is the change that needs to be made? I'm confused by the thread.

**Comment by jrhorn424** [comment]
I believe this is obsolete. Thanks @raq929.
