### ISSUE TITLE
Install other command line packages needed for tooling

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#97]
Note to self: research necessary global installs from template repositories.

**Comment by berziiii** [comment]
@jrhorn424 see commit fc4b734 where I scaffold the portion of the installfest for additional necessary global installs for NPM. Once we have more, we can add them to the command.

**Comment by jrhorn424** [comment]
Need:
- `remark-lint`
- `jscs`
- `bower`
- `ember`
